// Auto-generated by scripts/generate-core-manifest.mjs
export const CORE_CATALOG_MANIFEST = {
  "catalog_version": "core-20260330-v1",
  "generated_at": "2026-03-30T11:12:26.857Z",
  "selection_strategy": {
    "target_count": 300,
    "candidate_pool_size": 750,
    "minimum_per_element": 30,
    "ranking": "total accepted submissions"
  },
  "items": [
    {
      "title_slug": "two-sum",
      "title": "Two Sum",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table"
      ],
      "acceptance_rate": 0.5726,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-substring-without-repeating-characters",
      "title": "Longest Substring Without Repeating Characters",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "sliding-window"
      ],
      "acceptance_rate": 0.3875,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "best-time-to-buy-and-sell-stock",
      "title": "Best Time to Buy and Sell Stock",
      "difficulty": "Easy",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.5657,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-duplicates-from-sorted-array",
      "title": "Remove Duplicates from Sorted Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers"
      ],
      "acceptance_rate": 0.6251,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "contains-duplicate",
      "title": "Contains Duplicate",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "sorting"
      ],
      "acceptance_rate": 0.6418,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-linked-list",
      "title": "Reverse Linked List",
      "difficulty": "Easy",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "acceptance_rate": 0.8039,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-two-sorted-lists",
      "title": "Merge Two Sorted Lists",
      "difficulty": "Easy",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "acceptance_rate": 0.6809,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-anagram",
      "title": "Valid Anagram",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string",
        "sorting"
      ],
      "acceptance_rate": 0.6792,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "maximum-subarray",
      "title": "Maximum Subarray",
      "difficulty": "Medium",
      "tags": [
        "array",
        "divide-and-conquer",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.5312,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "3sum",
      "title": "3Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.388,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "roman-to-integer",
      "title": "Roman to Integer",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "math",
        "string"
      ],
      "acceptance_rate": 0.6643,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-common-prefix",
      "title": "Longest Common Prefix",
      "difficulty": "Easy",
      "tags": [
        "array",
        "string",
        "trie"
      ],
      "acceptance_rate": 0.473,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-sorted-array",
      "title": "Merge Sorted Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.5459,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "majority-element",
      "title": "Majority Element",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "divide-and-conquer",
        "sorting",
        "counting"
      ],
      "acceptance_rate": 0.6618,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "container-with-most-water",
      "title": "Container With Most Water",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "greedy"
      ],
      "acceptance_rate": 0.5975,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-element",
      "title": "Remove Element",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers"
      ],
      "acceptance_rate": 0.6156,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "move-zeroes",
      "title": "Move Zeroes",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers"
      ],
      "acceptance_rate": 0.6369,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "linked-list-cycle",
      "title": "Linked List Cycle",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.5408,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-insert-position",
      "title": "Search Insert Position",
      "difficulty": "Easy",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.5095,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "group-anagrams",
      "title": "Group Anagrams",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "string",
        "sorting"
      ],
      "acceptance_rate": 0.7236,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "single-number",
      "title": "Single Number",
      "difficulty": "Easy",
      "tags": [
        "array",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.775,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "product-of-array-except-self",
      "title": "Product of Array Except Self",
      "difficulty": "Medium",
      "tags": [
        "array",
        "prefix-sum"
      ],
      "acceptance_rate": 0.6873,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-in-rotated-sorted-array",
      "title": "Search in Rotated Sorted Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.443,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "median-of-two-sorted-arrays",
      "title": "Median of Two Sorted Arrays",
      "difficulty": "Hard",
      "tags": [
        "array",
        "binary-search",
        "divide-and-conquer"
      ],
      "acceptance_rate": 0.462,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-islands",
      "title": "Number of Islands",
      "difficulty": "Medium",
      "tags": [
        "array",
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "matrix"
      ],
      "acceptance_rate": 0.6407,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-intervals",
      "title": "Merge Intervals",
      "difficulty": "Medium",
      "tags": [
        "array",
        "sorting"
      ],
      "acceptance_rate": 0.5147,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "rotate-array",
      "title": "Rotate Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "math",
        "two-pointers"
      ],
      "acceptance_rate": 0.4466,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-search",
      "title": "Binary Search",
      "difficulty": "Easy",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.6067,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "missing-number",
      "title": "Missing Number",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "math",
        "binary-search",
        "bit-manipulation",
        "sorting"
      ],
      "acceptance_rate": 0.7179,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "plus-one",
      "title": "Plus One",
      "difficulty": "Easy",
      "tags": [
        "array",
        "math"
      ],
      "acceptance_rate": 0.4973,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "course-schedule",
      "title": "Course Schedule",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "topological-sort"
      ],
      "acceptance_rate": 0.5107,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "course-schedule-ii",
      "title": "Course Schedule II",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "topological-sort"
      ],
      "acceptance_rate": 0.552,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-provinces",
      "title": "Number of Provinces",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "graph"
      ],
      "acceptance_rate": 0.7015,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "is-graph-bipartite",
      "title": "Is Graph Bipartite?",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "graph"
      ],
      "acceptance_rate": 0.5905,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "network-delay-time",
      "title": "Network Delay Time",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "heap-priority-queue",
        "shortest-path"
      ],
      "acceptance_rate": 0.5999,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "all-paths-from-source-to-target",
      "title": "All Paths From Source to Target",
      "difficulty": "Medium",
      "tags": [
        "backtracking",
        "depth-first-search",
        "breadth-first-search",
        "graph"
      ],
      "acceptance_rate": 0.8357,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "keys-and-rooms",
      "title": "Keys and Rooms",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph"
      ],
      "acceptance_rate": 0.7561,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-if-path-exists-in-graph",
      "title": "Find if Path Exists in Graph",
      "difficulty": "Easy",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "graph"
      ],
      "acceptance_rate": 0.5492,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "redundant-connection",
      "title": "Redundant Connection",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "graph"
      ],
      "acceptance_rate": 0.6741,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-eventual-safe-states",
      "title": "Find Eventual Safe States",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "topological-sort"
      ],
      "acceptance_rate": 0.7047,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-height-trees",
      "title": "Minimum Height Trees",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "topological-sort"
      ],
      "acceptance_rate": 0.4246,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-center-of-star-graph",
      "title": "Find Center of Star Graph",
      "difficulty": "Easy",
      "tags": [
        "graph"
      ],
      "acceptance_rate": 0.8663,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "flatten-a-multilevel-doubly-linked-list",
      "title": "Flatten a Multilevel Doubly Linked List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "depth-first-search",
        "doubly-linked-list"
      ],
      "acceptance_rate": 0.6272,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "lexicographical-numbers",
      "title": "Lexicographical Numbers",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "trie"
      ],
      "acceptance_rate": 0.762,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-operations-to-make-network-connected",
      "title": "Number of Operations to Make Network Connected",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "graph"
      ],
      "acceptance_rate": 0.663,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "critical-connections-in-a-network",
      "title": "Critical Connections in a Network",
      "difficulty": "Hard",
      "tags": [
        "depth-first-search",
        "graph",
        "biconnected-component"
      ],
      "acceptance_rate": 0.5943,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reorder-routes-to-make-all-paths-lead-to-the-city-zero",
      "title": "Reorder Routes to Make All Paths Lead to the City Zero",
      "difficulty": "Medium",
      "tags": [
        "depth-first-search",
        "breadth-first-search",
        "graph"
      ],
      "acceptance_rate": 0.657,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "maximum-depth-of-binary-tree",
      "title": "Maximum Depth of Binary Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7803,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-inorder-traversal",
      "title": "Binary Tree Inorder Traversal",
      "difficulty": "Easy",
      "tags": [
        "stack",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7987,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "same-tree",
      "title": "Same Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6685,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-level-order-traversal",
      "title": "Binary Tree Level Order Traversal",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7239,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "validate-binary-search-tree",
      "title": "Validate Binary Search Tree",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.3552,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "invert-binary-tree",
      "title": "Invert Binary Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7993,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "symmetric-tree",
      "title": "Symmetric Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6094,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "lowest-common-ancestor-of-a-binary-tree",
      "title": "Lowest Common Ancestor of a Binary Tree",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6898,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "diameter-of-binary-tree",
      "title": "Diameter of Binary Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6527,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "balanced-binary-tree",
      "title": "Balanced Binary Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.5807,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-preorder-traversal",
      "title": "Binary Tree Preorder Traversal",
      "difficulty": "Easy",
      "tags": [
        "stack",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7542,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "lowest-common-ancestor-of-a-binary-search-tree",
      "title": "Lowest Common Ancestor of a Binary Search Tree",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.703,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "kth-smallest-element-in-a-bst",
      "title": "Kth Smallest Element in a BST",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.7662,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-right-side-view",
      "title": "Binary Tree Right Side View",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.698,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "path-sum",
      "title": "Path Sum",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.5462,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-postorder-traversal",
      "title": "Binary Tree Postorder Traversal",
      "difficulty": "Easy",
      "tags": [
        "stack",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7784,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-zigzag-level-order-traversal",
      "title": "Binary Tree Zigzag Level Order Traversal",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6339,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-depth-of-binary-tree",
      "title": "Minimum Depth of Binary Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.5259,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "flatten-binary-tree-to-linked-list",
      "title": "Flatten Binary Tree to Linked List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "stack",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7044,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-in-a-binary-search-tree",
      "title": "Search in a Binary Search Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.8257,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "range-sum-of-bst",
      "title": "Range Sum of BST",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.8758,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "populating-next-right-pointers-in-each-node",
      "title": "Populating Next Right Pointers in Each Node",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6699,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sum-root-to-leaf-numbers",
      "title": "Sum Root to Leaf Numbers",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6974,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "subtree-of-another-tree",
      "title": "Subtree of Another Tree",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "string-matching",
        "binary-tree",
        "hash-function"
      ],
      "acceptance_rate": 0.5139,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "path-sum-ii",
      "title": "Path Sum II",
      "difficulty": "Medium",
      "tags": [
        "backtracking",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6195,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-search-tree-iterator",
      "title": "Binary Search Tree Iterator",
      "difficulty": "Medium",
      "tags": [
        "stack",
        "tree",
        "design",
        "binary-search-tree",
        "binary-tree",
        "iterator"
      ],
      "acceptance_rate": 0.7628,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "kth-largest-element-in-a-stream",
      "title": "Kth Largest Element in a Stream",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "design",
        "binary-search-tree",
        "heap-priority-queue",
        "binary-tree",
        "data-stream"
      ],
      "acceptance_rate": 0.6082,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-two-binary-trees",
      "title": "Merge Two Binary Trees",
      "difficulty": "Easy",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.7902,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "count-good-nodes-in-binary-tree",
      "title": "Count Good Nodes in Binary Tree",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.738,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "insert-into-a-binary-search-tree",
      "title": "Insert into a Binary Search Tree",
      "difficulty": "Medium",
      "tags": [
        "tree",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.7341,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "palindrome-number",
      "title": "Palindrome Number",
      "difficulty": "Easy",
      "tags": [
        "math"
      ],
      "acceptance_rate": 0.604,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "add-two-numbers",
      "title": "Add Two Numbers",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "math",
        "recursion"
      ],
      "acceptance_rate": 0.4817,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "climbing-stairs",
      "title": "Climbing Stairs",
      "difficulty": "Easy",
      "tags": [
        "math",
        "dynamic-programming",
        "memoization"
      ],
      "acceptance_rate": 0.5398,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-integer",
      "title": "Reverse Integer",
      "difficulty": "Medium",
      "tags": [
        "math"
      ],
      "acceptance_rate": 0.3168,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sqrtx",
      "title": "Sqrt(x)",
      "difficulty": "Easy",
      "tags": [
        "math",
        "binary-search"
      ],
      "acceptance_rate": 0.416,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "fibonacci-number",
      "title": "Fibonacci Number",
      "difficulty": "Easy",
      "tags": [
        "math",
        "dynamic-programming",
        "recursion",
        "memoization"
      ],
      "acceptance_rate": 0.7399,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "unique-paths",
      "title": "Unique Paths",
      "difficulty": "Medium",
      "tags": [
        "math",
        "dynamic-programming",
        "combinatorics"
      ],
      "acceptance_rate": 0.6668,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "powx-n",
      "title": "Pow(x, n)",
      "difficulty": "Medium",
      "tags": [
        "math",
        "recursion"
      ],
      "acceptance_rate": 0.3844,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "add-binary",
      "title": "Add Binary",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string",
        "bit-manipulation",
        "simulation"
      ],
      "acceptance_rate": 0.5783,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "power-of-two",
      "title": "Power of Two",
      "difficulty": "Easy",
      "tags": [
        "math",
        "bit-manipulation",
        "recursion"
      ],
      "acceptance_rate": 0.4997,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-1-bits",
      "title": "Number of 1 Bits",
      "difficulty": "Easy",
      "tags": [
        "divide-and-conquer",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.7657,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "fizz-buzz",
      "title": "Fizz Buzz",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string",
        "simulation"
      ],
      "acceptance_rate": 0.7537,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "power-of-three",
      "title": "Power of Three",
      "difficulty": "Easy",
      "tags": [
        "math",
        "recursion"
      ],
      "acceptance_rate": 0.5089,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-bits",
      "title": "Reverse Bits",
      "difficulty": "Easy",
      "tags": [
        "divide-and-conquer",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.6805,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "add-digits",
      "title": "Add Digits",
      "difficulty": "Easy",
      "tags": [
        "math",
        "simulation",
        "number-theory"
      ],
      "acceptance_rate": 0.6876,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "multiply-strings",
      "title": "Multiply Strings",
      "difficulty": "Medium",
      "tags": [
        "math",
        "string",
        "simulation"
      ],
      "acceptance_rate": 0.4384,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "divide-two-integers",
      "title": "Divide Two Integers",
      "difficulty": "Medium",
      "tags": [
        "math",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.1954,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "power-of-four",
      "title": "Power of Four",
      "difficulty": "Easy",
      "tags": [
        "math",
        "bit-manipulation",
        "recursion"
      ],
      "acceptance_rate": 0.5188,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "n-th-tribonacci-number",
      "title": "N-th Tribonacci Number",
      "difficulty": "Easy",
      "tags": [
        "math",
        "dynamic-programming",
        "memoization"
      ],
      "acceptance_rate": 0.6323,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "perfect-squares",
      "title": "Perfect Squares",
      "difficulty": "Medium",
      "tags": [
        "math",
        "dynamic-programming",
        "breadth-first-search"
      ],
      "acceptance_rate": 0.5639,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "basic-calculator-ii",
      "title": "Basic Calculator II",
      "difficulty": "Medium",
      "tags": [
        "math",
        "string",
        "stack"
      ],
      "acceptance_rate": 0.4676,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "greatest-common-divisor-of-strings",
      "title": "Greatest Common Divisor of Strings",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string"
      ],
      "acceptance_rate": 0.5356,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "add-strings",
      "title": "Add Strings",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string",
        "simulation"
      ],
      "acceptance_rate": 0.5211,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-steps-to-reduce-a-number-to-zero",
      "title": "Number of Steps to Reduce a Number to Zero",
      "difficulty": "Easy",
      "tags": [
        "math",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.8576,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-perfect-square",
      "title": "Valid Perfect Square",
      "difficulty": "Easy",
      "tags": [
        "math",
        "binary-search"
      ],
      "acceptance_rate": 0.4478,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "excel-sheet-column-number",
      "title": "Excel Sheet Column Number",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string"
      ],
      "acceptance_rate": 0.6748,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "add-two-integers",
      "title": "Add Two Integers",
      "difficulty": "Easy",
      "tags": [
        "math"
      ],
      "acceptance_rate": 0.8795,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "unique-binary-search-trees",
      "title": "Unique Binary Search Trees",
      "difficulty": "Medium",
      "tags": [
        "math",
        "dynamic-programming",
        "tree",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.6346,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "ugly-number",
      "title": "Ugly Number",
      "difficulty": "Easy",
      "tags": [
        "math"
      ],
      "acceptance_rate": 0.4329,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "excel-sheet-column-title",
      "title": "Excel Sheet Column Title",
      "difficulty": "Easy",
      "tags": [
        "math",
        "string"
      ],
      "acceptance_rate": 0.4613,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-maximum-path-sum",
      "title": "Binary Tree Maximum Path Sum",
      "difficulty": "Hard",
      "tags": [
        "dynamic-programming",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.4213,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "counting-bits",
      "title": "Counting Bits",
      "difficulty": "Easy",
      "tags": [
        "dynamic-programming",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.8049,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "cheapest-flights-within-k-stops",
      "title": "Cheapest Flights Within K Stops",
      "difficulty": "Medium",
      "tags": [
        "dynamic-programming",
        "depth-first-search",
        "breadth-first-search",
        "graph",
        "heap-priority-queue",
        "shortest-path"
      ],
      "acceptance_rate": 0.4153,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "unique-binary-search-trees-ii",
      "title": "Unique Binary Search Trees II",
      "difficulty": "Medium",
      "tags": [
        "dynamic-programming",
        "backtracking",
        "tree",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.6216,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "house-robber-iii",
      "title": "House Robber III",
      "difficulty": "Medium",
      "tags": [
        "dynamic-programming",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.5574,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-dice-rolls-with-target-sum",
      "title": "Number of Dice Rolls With Target Sum",
      "difficulty": "Medium",
      "tags": [
        "dynamic-programming"
      ],
      "acceptance_rate": 0.6225,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
      "title": "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
      "difficulty": "Medium",
      "tags": [
        "dynamic-programming",
        "graph",
        "shortest-path"
      ],
      "acceptance_rate": 0.7238,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-parentheses",
      "title": "Valid Parentheses",
      "difficulty": "Easy",
      "tags": [
        "string",
        "stack"
      ],
      "acceptance_rate": 0.4392,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-palindrome",
      "title": "Valid Palindrome",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.5301,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-palindromic-substring",
      "title": "Longest Palindromic Substring",
      "difficulty": "Medium",
      "tags": [
        "two-pointers",
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.3755,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-nth-node-from-end-of-list",
      "title": "Remove Nth Node From End of List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.5124,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-the-index-of-the-first-occurrence-in-a-string",
      "title": "Find the Index of the First Occurrence in a String",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string",
        "string-matching"
      ],
      "acceptance_rate": 0.4642,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-string",
      "title": "Reverse String",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.8066,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "length-of-last-word",
      "title": "Length of Last Word",
      "difficulty": "Easy",
      "tags": [
        "string"
      ],
      "acceptance_rate": 0.5852,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "middle-of-the-linked-list",
      "title": "Middle of the Linked List",
      "difficulty": "Easy",
      "tags": [
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.8168,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-words-in-a-string",
      "title": "Reverse Words in a String",
      "difficulty": "Medium",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.5591,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "palindrome-linked-list",
      "title": "Palindrome Linked List",
      "difficulty": "Easy",
      "tags": [
        "linked-list",
        "two-pointers",
        "stack",
        "recursion"
      ],
      "acceptance_rate": 0.5766,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "generate-parentheses",
      "title": "Generate Parentheses",
      "difficulty": "Medium",
      "tags": [
        "string",
        "dynamic-programming",
        "backtracking"
      ],
      "acceptance_rate": 0.7846,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "is-subsequence",
      "title": "Is Subsequence",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.4892,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "string-to-integer-atoi",
      "title": "String to Integer (atoi)",
      "difficulty": "Medium",
      "tags": [
        "string"
      ],
      "acceptance_rate": 0.2076,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "zigzag-conversion",
      "title": "Zigzag Conversion",
      "difficulty": "Medium",
      "tags": [
        "string"
      ],
      "acceptance_rate": 0.5379,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-strings-alternately",
      "title": "Merge Strings Alternately",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.8209,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-common-subsequence",
      "title": "Longest Common Subsequence",
      "difficulty": "Medium",
      "tags": [
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.59,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "decode-ways",
      "title": "Decode Ways",
      "difficulty": "Medium",
      "tags": [
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.3777,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "rotate-list",
      "title": "Rotate List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.4144,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-vowels-of-a-string",
      "title": "Reverse Vowels of a String",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.6093,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reorder-list",
      "title": "Reorder List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "two-pointers",
        "stack",
        "recursion"
      ],
      "acceptance_rate": 0.649,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "edit-distance",
      "title": "Edit Distance",
      "difficulty": "Medium",
      "tags": [
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.6033,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "count-and-say",
      "title": "Count and Say",
      "difficulty": "Medium",
      "tags": [
        "string"
      ],
      "acceptance_rate": 0.6256,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "regular-expression-matching",
      "title": "Regular Expression Matching",
      "difficulty": "Hard",
      "tags": [
        "string",
        "dynamic-programming",
        "recursion"
      ],
      "acceptance_rate": 0.3065,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "palindrome-partitioning",
      "title": "Palindrome Partitioning",
      "difficulty": "Medium",
      "tags": [
        "string",
        "dynamic-programming",
        "backtracking"
      ],
      "acceptance_rate": 0.7384,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "simplify-path",
      "title": "Simplify Path",
      "difficulty": "Medium",
      "tags": [
        "string",
        "stack"
      ],
      "acceptance_rate": 0.5027,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sort-list",
      "title": "Sort List",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "two-pointers",
        "divide-and-conquer",
        "sorting",
        "merge-sort"
      ],
      "acceptance_rate": 0.6409,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-median-from-data-stream",
      "title": "Find Median from Data Stream",
      "difficulty": "Hard",
      "tags": [
        "two-pointers",
        "design",
        "sorting",
        "heap-priority-queue",
        "data-stream"
      ],
      "acceptance_rate": 0.543,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "serialize-and-deserialize-binary-tree",
      "title": "Serialize and Deserialize Binary Tree",
      "difficulty": "Hard",
      "tags": [
        "string",
        "tree",
        "depth-first-search",
        "breadth-first-search",
        "design",
        "binary-tree"
      ],
      "acceptance_rate": 0.6052,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "decode-string",
      "title": "Decode String",
      "difficulty": "Medium",
      "tags": [
        "string",
        "stack",
        "recursion"
      ],
      "acceptance_rate": 0.6241,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "palindromic-substrings",
      "title": "Palindromic Substrings",
      "difficulty": "Medium",
      "tags": [
        "two-pointers",
        "string",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.7265,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sort-colors",
      "title": "Sort Colors",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.6937,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "kth-largest-element-in-an-array",
      "title": "Kth Largest Element in an Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "divide-and-conquer",
        "sorting",
        "heap-priority-queue",
        "quickselect"
      ],
      "acceptance_rate": 0.6884,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "top-k-frequent-elements",
      "title": "Top K Frequent Elements",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "divide-and-conquer",
        "sorting",
        "heap-priority-queue",
        "bucket-sort",
        "counting",
        "quickselect"
      ],
      "acceptance_rate": 0.6613,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "house-robber",
      "title": "House Robber",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.5307,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "trapping-rain-water",
      "title": "Trapping Rain Water",
      "difficulty": "Hard",
      "tags": [
        "array",
        "two-pointers",
        "dynamic-programming",
        "stack",
        "monotonic-stack"
      ],
      "acceptance_rate": 0.6704,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "two-sum-ii-input-array-is-sorted",
      "title": "Two Sum II - Input Array Is Sorted",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "binary-search"
      ],
      "acceptance_rate": 0.6481,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-first-and-last-position-of-element-in-sorted-array",
      "title": "Find First and Last Position of Element in Sorted Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.4858,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-consecutive-sequence",
      "title": "Longest Consecutive Sequence",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "union-find"
      ],
      "acceptance_rate": 0.4705,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "jump-game",
      "title": "Jump Game",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "greedy"
      ],
      "acceptance_rate": 0.4065,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "combination-sum",
      "title": "Combination Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking"
      ],
      "acceptance_rate": 0.7629,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "permutations",
      "title": "Permutations",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking"
      ],
      "acceptance_rate": 0.8177,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "subsets",
      "title": "Subsets",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.8218,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "best-time-to-buy-and-sell-stock-ii",
      "title": "Best Time to Buy and Sell Stock II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "greedy"
      ],
      "acceptance_rate": 0.7088,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "letter-combinations-of-a-phone-number",
      "title": "Letter Combinations of a Phone Number",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "backtracking"
      ],
      "acceptance_rate": 0.6575,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-minimum-in-rotated-sorted-array",
      "title": "Find Minimum in Rotated Sorted Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.5397,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "merge-k-sorted-lists",
      "title": "Merge k Sorted Lists",
      "difficulty": "Hard",
      "tags": [
        "linked-list",
        "divide-and-conquer",
        "heap-priority-queue",
        "merge-sort"
      ],
      "acceptance_rate": 0.5919,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-a-2d-matrix",
      "title": "Search a 2D Matrix",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search",
        "matrix"
      ],
      "acceptance_rate": 0.5371,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "coin-change",
      "title": "Coin Change",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "breadth-first-search"
      ],
      "acceptance_rate": 0.4813,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "rotate-image",
      "title": "Rotate Image",
      "difficulty": "Medium",
      "tags": [
        "array",
        "math",
        "matrix"
      ],
      "acceptance_rate": 0.7951,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "min-stack",
      "title": "Min Stack",
      "difficulty": "Medium",
      "tags": [
        "stack",
        "design"
      ],
      "acceptance_rate": 0.579,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "pascals-triangle",
      "title": "Pascal's Triangle",
      "difficulty": "Easy",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.7878,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "squares-of-a-sorted-array",
      "title": "Squares of a Sorted Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.7366,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-increasing-subsequence",
      "title": "Longest Increasing Subsequence",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.592,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "lru-cache",
      "title": "LRU Cache",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "linked-list",
        "design",
        "doubly-linked-list"
      ],
      "acceptance_rate": 0.4707,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "set-matrix-zeroes",
      "title": "Set Matrix Zeroes",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "matrix"
      ],
      "acceptance_rate": 0.6264,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-the-duplicate-number",
      "title": "Find the Duplicate Number",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "binary-search",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.6413,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "word-search",
      "title": "Word Search",
      "difficulty": "Medium",
      "tags": [
        "array",
        "string",
        "backtracking",
        "depth-first-search",
        "matrix"
      ],
      "acceptance_rate": 0.4707,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-sudoku",
      "title": "Valid Sudoku",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "matrix"
      ],
      "acceptance_rate": 0.6431,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-peak-element",
      "title": "Find Peak Element",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.4685,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "subarray-sum-equals-k",
      "title": "Subarray Sum Equals K",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "prefix-sum"
      ],
      "acceptance_rate": 0.4704,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "running-sum-of-1d-array",
      "title": "Running Sum of 1d Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "prefix-sum"
      ],
      "acceptance_rate": 0.8692,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "recyclable-and-low-fat-products",
      "title": "Recyclable and Low Fat Products",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.8871,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "word-break",
      "title": "Word Break",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "string",
        "dynamic-programming",
        "trie",
        "memoization"
      ],
      "acceptance_rate": 0.4926,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "first-unique-character-in-a-string",
      "title": "First Unique Character in a String",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string",
        "queue",
        "counting"
      ],
      "acceptance_rate": 0.6523,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "intersection-of-two-linked-lists",
      "title": "Intersection of Two Linked Lists",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.6344,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "spiral-matrix",
      "title": "Spiral Matrix",
      "difficulty": "Medium",
      "tags": [
        "array",
        "matrix",
        "simulation"
      ],
      "acceptance_rate": 0.5642,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-duplicates-from-sorted-list",
      "title": "Remove Duplicates from Sorted List",
      "difficulty": "Easy",
      "tags": [
        "linked-list"
      ],
      "acceptance_rate": 0.5647,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "big-countries",
      "title": "Big Countries",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.6843,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "happy-number",
      "title": "Happy Number",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "math",
        "two-pointers"
      ],
      "acceptance_rate": 0.5942,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "next-permutation",
      "title": "Next Permutation",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers"
      ],
      "acceptance_rate": 0.4496,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "max-consecutive-ones",
      "title": "Max Consecutive Ones",
      "difficulty": "Easy",
      "tags": [
        "array"
      ],
      "acceptance_rate": 0.6485,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "first-bad-version",
      "title": "First Bad Version",
      "difficulty": "Easy",
      "tags": [
        "binary-search",
        "interactive"
      ],
      "acceptance_rate": 0.4697,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "isomorphic-strings",
      "title": "Isomorphic Strings",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string"
      ],
      "acceptance_rate": 0.482,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-window-substring",
      "title": "Minimum Window Substring",
      "difficulty": "Hard",
      "tags": [
        "hash-table",
        "string",
        "sliding-window"
      ],
      "acceptance_rate": 0.472,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "jump-game-ii",
      "title": "Jump Game II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "greedy"
      ],
      "acceptance_rate": 0.4263,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "integer-to-roman",
      "title": "Integer to Roman",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "math",
        "string"
      ],
      "acceptance_rate": 0.7068,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-customer-referee",
      "title": "Find Customer Referee",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7269,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "delete-node-in-a-linked-list",
      "title": "Delete Node in a Linked List",
      "difficulty": "Medium",
      "tags": [
        "linked-list"
      ],
      "acceptance_rate": 0.8371,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "maximum-product-subarray",
      "title": "Maximum Product Subarray",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.3618,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "linked-list-cycle-ii",
      "title": "Linked List Cycle II",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.5754,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "ransom-note",
      "title": "Ransom Note",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string",
        "counting"
      ],
      "acceptance_rate": 0.6577,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-duplicates-from-sorted-array-ii",
      "title": "Remove Duplicates from Sorted Array II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers"
      ],
      "acceptance_rate": 0.6445,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "swap-nodes-in-pairs",
      "title": "Swap Nodes in Pairs",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "acceptance_rate": 0.692,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "copy-list-with-random-pointer",
      "title": "Copy List with Random Pointer",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "linked-list"
      ],
      "acceptance_rate": 0.626,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "clone-graph",
      "title": "Clone Graph",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "depth-first-search",
        "breadth-first-search",
        "graph"
      ],
      "acceptance_rate": 0.6495,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
      "title": "Construct Binary Tree from Preorder and Inorder Traversal",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "divide-and-conquer",
        "tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.6856,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-size-subarray-sum",
      "title": "Minimum Size Subarray Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search",
        "sliding-window",
        "prefix-sum"
      ],
      "acceptance_rate": 0.5132,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "intersection-of-two-arrays",
      "title": "Intersection of Two Arrays",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "two-pointers",
        "binary-search",
        "sorting"
      ],
      "acceptance_rate": 0.7761,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-path-sum",
      "title": "Minimum Path Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "matrix"
      ],
      "acceptance_rate": 0.68,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "3sum-closest",
      "title": "3Sum Closest",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.4827,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "combine-two-tables",
      "title": "Combine Two Tables",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7937,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "insert-interval",
      "title": "Insert Interval",
      "difficulty": "Medium",
      "tags": [
        "array"
      ],
      "acceptance_rate": 0.4495,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "contains-duplicate-ii",
      "title": "Contains Duplicate II",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "sliding-window"
      ],
      "acceptance_rate": 0.5101,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "min-cost-climbing-stairs",
      "title": "Min Cost Climbing Stairs",
      "difficulty": "Easy",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.6813,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "first-missing-positive",
      "title": "First Missing Positive",
      "difficulty": "Hard",
      "tags": [
        "array",
        "hash-table"
      ],
      "acceptance_rate": 0.4264,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "intersection-of-two-arrays-ii",
      "title": "Intersection of Two Arrays II",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "two-pointers",
        "binary-search",
        "sorting"
      ],
      "acceptance_rate": 0.5978,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "evaluate-reverse-polish-notation",
      "title": "Evaluate Reverse Polish Notation",
      "difficulty": "Medium",
      "tags": [
        "array",
        "math",
        "stack"
      ],
      "acceptance_rate": 0.5734,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "k-closest-points-to-origin",
      "title": "K Closest Points to Origin",
      "difficulty": "Medium",
      "tags": [
        "array",
        "math",
        "divide-and-conquer",
        "geometry",
        "sorting",
        "heap-priority-queue",
        "quickselect"
      ],
      "acceptance_rate": 0.6885,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "convert-sorted-array-to-binary-search-tree",
      "title": "Convert Sorted Array to Binary Search Tree",
      "difficulty": "Easy",
      "tags": [
        "array",
        "divide-and-conquer",
        "tree",
        "binary-search-tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.7536,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "combination-sum-ii",
      "title": "Combination Sum II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking"
      ],
      "acceptance_rate": 0.5918,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "daily-temperatures",
      "title": "Daily Temperatures",
      "difficulty": "Medium",
      "tags": [
        "array",
        "stack",
        "monotonic-stack"
      ],
      "acceptance_rate": 0.685,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "4sum",
      "title": "4Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.4027,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-pivot-index",
      "title": "Find Pivot Index",
      "difficulty": "Easy",
      "tags": [
        "array",
        "prefix-sum"
      ],
      "acceptance_rate": 0.6236,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sliding-window-maximum",
      "title": "Sliding Window Maximum",
      "difficulty": "Hard",
      "tags": [
        "array",
        "queue",
        "sliding-window",
        "heap-priority-queue",
        "monotonic-queue"
      ],
      "acceptance_rate": 0.4858,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "rotting-oranges",
      "title": "Rotting Oranges",
      "difficulty": "Medium",
      "tags": [
        "array",
        "breadth-first-search",
        "matrix"
      ],
      "acceptance_rate": 0.5836,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "article-views-i",
      "title": "Article Views I",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.767,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "word-ladder",
      "title": "Word Ladder",
      "difficulty": "Hard",
      "tags": [
        "hash-table",
        "string",
        "breadth-first-search"
      ],
      "acceptance_rate": 0.4518,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-linked-list-elements",
      "title": "Remove Linked List Elements",
      "difficulty": "Easy",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "acceptance_rate": 0.5413,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "koko-eating-bananas",
      "title": "Koko Eating Bananas",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.4984,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "largest-rectangle-in-histogram",
      "title": "Largest Rectangle in Histogram",
      "difficulty": "Hard",
      "tags": [
        "array",
        "stack",
        "monotonic-stack"
      ],
      "acceptance_rate": 0.4956,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "implement-trie-prefix-tree",
      "title": "Implement Trie (Prefix Tree)",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "design",
        "trie"
      ],
      "acceptance_rate": 0.6931,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-repeating-character-replacement",
      "title": "Longest Repeating Character Replacement",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "sliding-window"
      ],
      "acceptance_rate": 0.5929,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-nodes-in-k-group",
      "title": "Reverse Nodes in k-Group",
      "difficulty": "Hard",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "acceptance_rate": 0.6567,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "second-highest-salary",
      "title": "Second Highest Salary",
      "difficulty": "Medium",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.4663,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "kids-with-the-greatest-number-of-candies",
      "title": "Kids With the Greatest Number of Candies",
      "difficulty": "Easy",
      "tags": [
        "array"
      ],
      "acceptance_rate": 0.8803,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "partition-equal-subset-sum",
      "title": "Partition Equal Subset Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.4932,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "odd-even-linked-list",
      "title": "Odd Even Linked List",
      "difficulty": "Medium",
      "tags": [
        "linked-list"
      ],
      "acceptance_rate": 0.6239,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "subsets-ii",
      "title": "Subsets II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking",
        "bit-manipulation"
      ],
      "acceptance_rate": 0.6106,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "rising-temperature",
      "title": "Rising Temperature",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.5112,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "permutation-in-string",
      "title": "Permutation in String",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "two-pointers",
        "string",
        "sliding-window"
      ],
      "acceptance_rate": 0.4862,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "implement-queue-using-stacks",
      "title": "Implement Queue using Stacks",
      "difficulty": "Easy",
      "tags": [
        "stack",
        "design",
        "queue"
      ],
      "acceptance_rate": 0.6954,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "unique-paths-ii",
      "title": "Unique Paths II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "matrix"
      ],
      "acceptance_rate": 0.4429,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "concatenation-of-array",
      "title": "Concatenation of Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "simulation"
      ],
      "acceptance_rate": 0.9045,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "invalid-tweets",
      "title": "Invalid Tweets",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.8517,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "next-greater-element-i",
      "title": "Next Greater Element I",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "stack",
        "monotonic-stack"
      ],
      "acceptance_rate": 0.7593,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "flood-fill",
      "title": "Flood Fill",
      "difficulty": "Easy",
      "tags": [
        "array",
        "depth-first-search",
        "breadth-first-search",
        "matrix"
      ],
      "acceptance_rate": 0.68,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "can-place-flowers",
      "title": "Can Place Flowers",
      "difficulty": "Easy",
      "tags": [
        "array",
        "greedy"
      ],
      "acceptance_rate": 0.2908,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "jewels-and-stones",
      "title": "Jewels and Stones",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string"
      ],
      "acceptance_rate": 0.8952,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "max-consecutive-ones-iii",
      "title": "Max Consecutive Ones III",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search",
        "sliding-window",
        "prefix-sum"
      ],
      "acceptance_rate": 0.6747,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-all-numbers-disappeared-in-an-array",
      "title": "Find All Numbers Disappeared in an Array",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table"
      ],
      "acceptance_rate": 0.6393,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-a-2d-matrix-ii",
      "title": "Search a 2D Matrix II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search",
        "divide-and-conquer",
        "matrix"
      ],
      "acceptance_rate": 0.5702,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "insert-delete-getrandom-o1",
      "title": "Insert Delete GetRandom O(1)",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "math",
        "design",
        "randomized"
      ],
      "acceptance_rate": 0.5532,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "gas-station",
      "title": "Gas Station",
      "difficulty": "Medium",
      "tags": [
        "array",
        "greedy"
      ],
      "acceptance_rate": 0.4772,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "combinations",
      "title": "Combinations",
      "difficulty": "Medium",
      "tags": [
        "backtracking"
      ],
      "acceptance_rate": 0.7437,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "product-sales-analysis-i",
      "title": "Product Sales Analysis I",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.8566,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "replace-employee-id-with-the-unique-identifier",
      "title": "Replace Employee ID With The Unique Identifier",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.8354,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-linked-list-ii",
      "title": "Reverse Linked List II",
      "difficulty": "Medium",
      "tags": [
        "linked-list"
      ],
      "acceptance_rate": 0.5122,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "customers-who-never-order",
      "title": "Customers Who Never Order",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.716,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "triangle",
      "title": "Triangle",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.5986,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "permutations-ii",
      "title": "Permutations II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "backtracking",
        "sorting"
      ],
      "acceptance_rate": 0.6317,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "count-primes",
      "title": "Count Primes",
      "difficulty": "Medium",
      "tags": [
        "array",
        "math",
        "enumeration",
        "number-theory"
      ],
      "acceptance_rate": 0.3588,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "n-queens",
      "title": "N-Queens",
      "difficulty": "Hard",
      "tags": [
        "array",
        "backtracking"
      ],
      "acceptance_rate": 0.7519,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "majority-element-ii",
      "title": "Majority Element II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "sorting",
        "counting"
      ],
      "acceptance_rate": 0.5596,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "house-robber-ii",
      "title": "House Robber II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.4473,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "max-area-of-island",
      "title": "Max Area of Island",
      "difficulty": "Medium",
      "tags": [
        "array",
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "matrix"
      ],
      "acceptance_rate": 0.7387,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "richest-customer-wealth",
      "title": "Richest Customer Wealth",
      "difficulty": "Easy",
      "tags": [
        "array",
        "matrix"
      ],
      "acceptance_rate": 0.8868,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "search-in-rotated-sorted-array-ii",
      "title": "Search in Rotated Sorted Array II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.3986,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "pascals-triangle-ii",
      "title": "Pascal's Triangle II",
      "difficulty": "Easy",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.6725,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "single-element-in-a-sorted-array",
      "title": "Single Element in a Sorted Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.5924,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-all-anagrams-in-a-string",
      "title": "Find All Anagrams in a String",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "sliding-window"
      ],
      "acceptance_rate": 0.535,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "peak-index-in-a-mountain-array",
      "title": "Peak Index in a Mountain Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "binary-search"
      ],
      "acceptance_rate": 0.6688,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "surrounded-regions",
      "title": "Surrounded Regions",
      "difficulty": "Medium",
      "tags": [
        "array",
        "depth-first-search",
        "breadth-first-search",
        "union-find",
        "matrix"
      ],
      "acceptance_rate": 0.4497,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "maximum-average-subarray-i",
      "title": "Maximum Average Subarray I",
      "difficulty": "Easy",
      "tags": [
        "array",
        "sliding-window"
      ],
      "acceptance_rate": 0.4742,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "count-complete-tree-nodes",
      "title": "Count Complete Tree Nodes",
      "difficulty": "Easy",
      "tags": [
        "binary-search",
        "bit-manipulation",
        "tree",
        "binary-tree"
      ],
      "acceptance_rate": 0.7228,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "duplicate-emails",
      "title": "Duplicate Emails",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7356,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "customer-who-visited-but-did-not-make-any-transactions",
      "title": "Customer Who Visited but Did Not Make Any Transactions",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.6762,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "employees-earning-more-than-their-managers",
      "title": "Employees Earning More Than Their Managers",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7303,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "implement-stack-using-queues",
      "title": "Implement Stack using Queues",
      "difficulty": "Easy",
      "tags": [
        "stack",
        "design",
        "queue"
      ],
      "acceptance_rate": 0.6959,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "valid-palindrome-ii",
      "title": "Valid Palindrome II",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string",
        "greedy"
      ],
      "acceptance_rate": 0.4409,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "reverse-words-in-a-string-iii",
      "title": "Reverse Words in a String III",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.8396,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sort-an-array",
      "title": "Sort an Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "divide-and-conquer",
        "sorting",
        "heap-priority-queue",
        "merge-sort",
        "bucket-sort",
        "radix-sort",
        "counting-sort"
      ],
      "acceptance_rate": 0.559,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sort-characters-by-frequency",
      "title": "Sort Characters By Frequency",
      "difficulty": "Medium",
      "tags": [
        "hash-table",
        "string",
        "sorting",
        "heap-priority-queue",
        "bucket-sort",
        "counting"
      ],
      "acceptance_rate": 0.752,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "word-pattern",
      "title": "Word Pattern",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string"
      ],
      "acceptance_rate": 0.4394,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "not-boring-movies",
      "title": "Not Boring Movies",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7511,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "remove-duplicates-from-sorted-list-ii",
      "title": "Remove Duplicates from Sorted List II",
      "difficulty": "Medium",
      "tags": [
        "linked-list",
        "two-pointers"
      ],
      "acceptance_rate": 0.5152,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-valid-parentheses",
      "title": "Longest Valid Parentheses",
      "difficulty": "Hard",
      "tags": [
        "string",
        "dynamic-programming",
        "stack"
      ],
      "acceptance_rate": 0.3838,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-the-difference",
      "title": "Find the Difference",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string",
        "bit-manipulation",
        "sorting"
      ],
      "acceptance_rate": 0.6022,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "target-sum",
      "title": "Target Sum",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "backtracking"
      ],
      "acceptance_rate": 0.5199,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-numbers-with-even-number-of-digits",
      "title": "Find Numbers with Even Number of Digits",
      "difficulty": "Easy",
      "tags": [
        "array",
        "math"
      ],
      "acceptance_rate": 0.7969,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "string-compression",
      "title": "String Compression",
      "difficulty": "Medium",
      "tags": [
        "two-pointers",
        "string"
      ],
      "acceptance_rate": 0.5975,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "shuffle-the-array",
      "title": "Shuffle the Array",
      "difficulty": "Easy",
      "tags": [
        "array"
      ],
      "acceptance_rate": 0.8892,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "minimum-remove-to-make-valid-parentheses",
      "title": "Minimum Remove to Make Valid Parentheses",
      "difficulty": "Medium",
      "tags": [
        "string",
        "stack"
      ],
      "acceptance_rate": 0.7135,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "employee-bonus",
      "title": "Employee Bonus",
      "difficulty": "Easy",
      "tags": [
        "database"
      ],
      "acceptance_rate": 0.7728,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "number-of-good-pairs",
      "title": "Number of Good Pairs",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table",
        "math",
        "counting"
      ],
      "acceptance_rate": 0.898,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "longest-palindrome",
      "title": "Longest Palindrome",
      "difficulty": "Easy",
      "tags": [
        "hash-table",
        "string",
        "greedy"
      ],
      "acceptance_rate": 0.559,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "backspace-string-compare",
      "title": "Backspace String Compare",
      "difficulty": "Easy",
      "tags": [
        "two-pointers",
        "string",
        "stack",
        "simulation"
      ],
      "acceptance_rate": 0.4982,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "find-all-duplicates-in-an-array",
      "title": "Find All Duplicates in an Array",
      "difficulty": "Medium",
      "tags": [
        "array",
        "hash-table",
        "sorting"
      ],
      "acceptance_rate": 0.7686,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "candy",
      "title": "Candy",
      "difficulty": "Hard",
      "tags": [
        "array",
        "greedy"
      ],
      "acceptance_rate": 0.4818,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sudoku-solver",
      "title": "Sudoku Solver",
      "difficulty": "Hard",
      "tags": [
        "array",
        "hash-table",
        "backtracking",
        "matrix"
      ],
      "acceptance_rate": 0.6541,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "sort-array-by-parity",
      "title": "Sort Array By Parity",
      "difficulty": "Easy",
      "tags": [
        "array",
        "two-pointers",
        "sorting"
      ],
      "acceptance_rate": 0.7649,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "binary-tree-paths",
      "title": "Binary Tree Paths",
      "difficulty": "Easy",
      "tags": [
        "string",
        "backtracking",
        "tree",
        "depth-first-search",
        "binary-tree"
      ],
      "acceptance_rate": 0.6839,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "guess-number-higher-or-lower",
      "title": "Guess Number Higher or Lower",
      "difficulty": "Easy",
      "tags": [
        "binary-search",
        "interactive"
      ],
      "acceptance_rate": 0.5731,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "asteroid-collision",
      "title": "Asteroid Collision",
      "difficulty": "Medium",
      "tags": [
        "array",
        "stack",
        "simulation"
      ],
      "acceptance_rate": 0.4745,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "non-overlapping-intervals",
      "title": "Non-overlapping Intervals",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming",
        "greedy",
        "sorting"
      ],
      "acceptance_rate": 0.569,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "coin-change-ii",
      "title": "Coin Change II",
      "difficulty": "Medium",
      "tags": [
        "array",
        "dynamic-programming"
      ],
      "acceptance_rate": 0.6028,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    },
    {
      "title_slug": "unique-number-of-occurrences",
      "title": "Unique Number of Occurrences",
      "difficulty": "Easy",
      "tags": [
        "array",
        "hash-table"
      ],
      "acceptance_rate": 0.7866,
      "is_free": true,
      "catalog_version": "core-20260330-v1"
    }
  ]
} as const;

